use std::env::args;

use typst_assets::html::ELEMS;

fn main() {
    let args: Vec<_> = args().collect();
    assert_eq!(args.len(), 2, r#"must get one argument (a module, usually either `std.html` (unquoted) or `"polyfill.typ"` (quoted)"#);
    let module = &args[1];

    println!("// This file is generated by `typed-html/src/main.rs`; do not edit by hand. See");
    println!("//   https://github.com/typst/typst-assets/blob/fbf00f9539fdb0825bef4d39fb57d5986c51b756/files/html/data.rs");
    println!("// For details.");
    println!();
    println!("#import {module}: elem, frame");

    for elem in ELEMS {
        println!();
        println!(r#"#let {name}(..args) = elem("{name}", ..args.pos(), attrs: args.named())"#, name=elem.name);
    }
}
