use typst_assets::html::ELEMS;

fn main() {
    println!("// This file is generated by `typed-html/src/main.rs`; do not edit by hand. See");
    println!("//   https://github.com/typst/typst-assets/blob/fbf00f9539fdb0825bef4d39fb57d5986c51b756/files/html/data.rs");
    println!("// For details.");

    for elem in ELEMS {
        println!();
        println!(r#"#let {name}(..args) = context panic("bullseye's html.{name}() must not be present when compiling a document to PDF/SVG/...")"#, name=elem.name);
    }
}
