// This file is generated by `typed-html/src/main.rs`; do not edit by hand. See
//   https://github.com/typst/typst-assets/blob/fbf00f9539fdb0825bef4d39fb57d5986c51b756/files/html/data.rs
// For details.

#import "polyfill.typ": elem, frame

#let a(..args) = elem("a", ..args.pos(), attrs: args.named())

#let abbr(..args) = elem("abbr", ..args.pos(), attrs: args.named())

#let address(..args) = elem("address", ..args.pos(), attrs: args.named())

#let area(..args) = elem("area", ..args.pos(), attrs: args.named())

#let article(..args) = elem("article", ..args.pos(), attrs: args.named())

#let aside(..args) = elem("aside", ..args.pos(), attrs: args.named())

#let audio(..args) = elem("audio", ..args.pos(), attrs: args.named())

#let b(..args) = elem("b", ..args.pos(), attrs: args.named())

#let base(..args) = elem("base", ..args.pos(), attrs: args.named())

#let bdi(..args) = elem("bdi", ..args.pos(), attrs: args.named())

#let bdo(..args) = elem("bdo", ..args.pos(), attrs: args.named())

#let blockquote(..args) = elem("blockquote", ..args.pos(), attrs: args.named())

#let body(..args) = elem("body", ..args.pos(), attrs: args.named())

#let br(..args) = elem("br", ..args.pos(), attrs: args.named())

#let button(..args) = elem("button", ..args.pos(), attrs: args.named())

#let canvas(..args) = elem("canvas", ..args.pos(), attrs: args.named())

#let caption(..args) = elem("caption", ..args.pos(), attrs: args.named())

#let cite(..args) = elem("cite", ..args.pos(), attrs: args.named())

#let code(..args) = elem("code", ..args.pos(), attrs: args.named())

#let col(..args) = elem("col", ..args.pos(), attrs: args.named())

#let colgroup(..args) = elem("colgroup", ..args.pos(), attrs: args.named())

#let data(..args) = elem("data", ..args.pos(), attrs: args.named())

#let datalist(..args) = elem("datalist", ..args.pos(), attrs: args.named())

#let dd(..args) = elem("dd", ..args.pos(), attrs: args.named())

#let del(..args) = elem("del", ..args.pos(), attrs: args.named())

#let details(..args) = elem("details", ..args.pos(), attrs: args.named())

#let dfn(..args) = elem("dfn", ..args.pos(), attrs: args.named())

#let dialog(..args) = elem("dialog", ..args.pos(), attrs: args.named())

#let div(..args) = elem("div", ..args.pos(), attrs: args.named())

#let dl(..args) = elem("dl", ..args.pos(), attrs: args.named())

#let dt(..args) = elem("dt", ..args.pos(), attrs: args.named())

#let em(..args) = elem("em", ..args.pos(), attrs: args.named())

#let embed(..args) = elem("embed", ..args.pos(), attrs: args.named())

#let fieldset(..args) = elem("fieldset", ..args.pos(), attrs: args.named())

#let figcaption(..args) = elem("figcaption", ..args.pos(), attrs: args.named())

#let figure(..args) = elem("figure", ..args.pos(), attrs: args.named())

#let footer(..args) = elem("footer", ..args.pos(), attrs: args.named())

#let form(..args) = elem("form", ..args.pos(), attrs: args.named())

#let h1(..args) = elem("h1", ..args.pos(), attrs: args.named())

#let h2(..args) = elem("h2", ..args.pos(), attrs: args.named())

#let h3(..args) = elem("h3", ..args.pos(), attrs: args.named())

#let h4(..args) = elem("h4", ..args.pos(), attrs: args.named())

#let h5(..args) = elem("h5", ..args.pos(), attrs: args.named())

#let h6(..args) = elem("h6", ..args.pos(), attrs: args.named())

#let head(..args) = elem("head", ..args.pos(), attrs: args.named())

#let header(..args) = elem("header", ..args.pos(), attrs: args.named())

#let hgroup(..args) = elem("hgroup", ..args.pos(), attrs: args.named())

#let hr(..args) = elem("hr", ..args.pos(), attrs: args.named())

#let html(..args) = elem("html", ..args.pos(), attrs: args.named())

#let i(..args) = elem("i", ..args.pos(), attrs: args.named())

#let iframe(..args) = elem("iframe", ..args.pos(), attrs: args.named())

#let img(..args) = elem("img", ..args.pos(), attrs: args.named())

#let input(..args) = elem("input", ..args.pos(), attrs: args.named())

#let ins(..args) = elem("ins", ..args.pos(), attrs: args.named())

#let kbd(..args) = elem("kbd", ..args.pos(), attrs: args.named())

#let label(..args) = elem("label", ..args.pos(), attrs: args.named())

#let legend(..args) = elem("legend", ..args.pos(), attrs: args.named())

#let li(..args) = elem("li", ..args.pos(), attrs: args.named())

#let link(..args) = elem("link", ..args.pos(), attrs: args.named())

#let main(..args) = elem("main", ..args.pos(), attrs: args.named())

#let map(..args) = elem("map", ..args.pos(), attrs: args.named())

#let mark(..args) = elem("mark", ..args.pos(), attrs: args.named())

#let menu(..args) = elem("menu", ..args.pos(), attrs: args.named())

#let meta(..args) = elem("meta", ..args.pos(), attrs: args.named())

#let meter(..args) = elem("meter", ..args.pos(), attrs: args.named())

#let nav(..args) = elem("nav", ..args.pos(), attrs: args.named())

#let noscript(..args) = elem("noscript", ..args.pos(), attrs: args.named())

#let object(..args) = elem("object", ..args.pos(), attrs: args.named())

#let ol(..args) = elem("ol", ..args.pos(), attrs: args.named())

#let optgroup(..args) = elem("optgroup", ..args.pos(), attrs: args.named())

#let option(..args) = elem("option", ..args.pos(), attrs: args.named())

#let output(..args) = elem("output", ..args.pos(), attrs: args.named())

#let p(..args) = elem("p", ..args.pos(), attrs: args.named())

#let picture(..args) = elem("picture", ..args.pos(), attrs: args.named())

#let pre(..args) = elem("pre", ..args.pos(), attrs: args.named())

#let progress(..args) = elem("progress", ..args.pos(), attrs: args.named())

#let q(..args) = elem("q", ..args.pos(), attrs: args.named())

#let rp(..args) = elem("rp", ..args.pos(), attrs: args.named())

#let rt(..args) = elem("rt", ..args.pos(), attrs: args.named())

#let ruby(..args) = elem("ruby", ..args.pos(), attrs: args.named())

#let s(..args) = elem("s", ..args.pos(), attrs: args.named())

#let samp(..args) = elem("samp", ..args.pos(), attrs: args.named())

#let script(..args) = elem("script", ..args.pos(), attrs: args.named())

#let search(..args) = elem("search", ..args.pos(), attrs: args.named())

#let section(..args) = elem("section", ..args.pos(), attrs: args.named())

#let select(..args) = elem("select", ..args.pos(), attrs: args.named())

#let slot(..args) = elem("slot", ..args.pos(), attrs: args.named())

#let small(..args) = elem("small", ..args.pos(), attrs: args.named())

#let source(..args) = elem("source", ..args.pos(), attrs: args.named())

#let span(..args) = elem("span", ..args.pos(), attrs: args.named())

#let strong(..args) = elem("strong", ..args.pos(), attrs: args.named())

#let style(..args) = elem("style", ..args.pos(), attrs: args.named())

#let sub(..args) = elem("sub", ..args.pos(), attrs: args.named())

#let summary(..args) = elem("summary", ..args.pos(), attrs: args.named())

#let sup(..args) = elem("sup", ..args.pos(), attrs: args.named())

#let table(..args) = elem("table", ..args.pos(), attrs: args.named())

#let tbody(..args) = elem("tbody", ..args.pos(), attrs: args.named())

#let td(..args) = elem("td", ..args.pos(), attrs: args.named())

#let template(..args) = elem("template", ..args.pos(), attrs: args.named())

#let textarea(..args) = elem("textarea", ..args.pos(), attrs: args.named())

#let tfoot(..args) = elem("tfoot", ..args.pos(), attrs: args.named())

#let th(..args) = elem("th", ..args.pos(), attrs: args.named())

#let thead(..args) = elem("thead", ..args.pos(), attrs: args.named())

#let time(..args) = elem("time", ..args.pos(), attrs: args.named())

#let title(..args) = elem("title", ..args.pos(), attrs: args.named())

#let tr(..args) = elem("tr", ..args.pos(), attrs: args.named())

#let track(..args) = elem("track", ..args.pos(), attrs: args.named())

#let u(..args) = elem("u", ..args.pos(), attrs: args.named())

#let ul(..args) = elem("ul", ..args.pos(), attrs: args.named())

#let var(..args) = elem("var", ..args.pos(), attrs: args.named())

#let video(..args) = elem("video", ..args.pos(), attrs: args.named())

#let wbr(..args) = elem("wbr", ..args.pos(), attrs: args.named())
