// This file is generated by `typed-html/src/main.rs`; do not edit by hand. See
//   https://github.com/typst/typst-assets/blob/fbf00f9539fdb0825bef4d39fb57d5986c51b756/files/html/data.rs
// For details.

#let a(..args) = context panic("bullseye's html.a() must not be present when compiling a document to PDF/SVG/...")

#let abbr(..args) = context panic("bullseye's html.abbr() must not be present when compiling a document to PDF/SVG/...")

#let address(..args) = context panic("bullseye's html.address() must not be present when compiling a document to PDF/SVG/...")

#let area(..args) = context panic("bullseye's html.area() must not be present when compiling a document to PDF/SVG/...")

#let article(..args) = context panic("bullseye's html.article() must not be present when compiling a document to PDF/SVG/...")

#let aside(..args) = context panic("bullseye's html.aside() must not be present when compiling a document to PDF/SVG/...")

#let audio(..args) = context panic("bullseye's html.audio() must not be present when compiling a document to PDF/SVG/...")

#let b(..args) = context panic("bullseye's html.b() must not be present when compiling a document to PDF/SVG/...")

#let base(..args) = context panic("bullseye's html.base() must not be present when compiling a document to PDF/SVG/...")

#let bdi(..args) = context panic("bullseye's html.bdi() must not be present when compiling a document to PDF/SVG/...")

#let bdo(..args) = context panic("bullseye's html.bdo() must not be present when compiling a document to PDF/SVG/...")

#let blockquote(..args) = context panic("bullseye's html.blockquote() must not be present when compiling a document to PDF/SVG/...")

#let body(..args) = context panic("bullseye's html.body() must not be present when compiling a document to PDF/SVG/...")

#let br(..args) = context panic("bullseye's html.br() must not be present when compiling a document to PDF/SVG/...")

#let button(..args) = context panic("bullseye's html.button() must not be present when compiling a document to PDF/SVG/...")

#let canvas(..args) = context panic("bullseye's html.canvas() must not be present when compiling a document to PDF/SVG/...")

#let caption(..args) = context panic("bullseye's html.caption() must not be present when compiling a document to PDF/SVG/...")

#let cite(..args) = context panic("bullseye's html.cite() must not be present when compiling a document to PDF/SVG/...")

#let code(..args) = context panic("bullseye's html.code() must not be present when compiling a document to PDF/SVG/...")

#let col(..args) = context panic("bullseye's html.col() must not be present when compiling a document to PDF/SVG/...")

#let colgroup(..args) = context panic("bullseye's html.colgroup() must not be present when compiling a document to PDF/SVG/...")

#let data(..args) = context panic("bullseye's html.data() must not be present when compiling a document to PDF/SVG/...")

#let datalist(..args) = context panic("bullseye's html.datalist() must not be present when compiling a document to PDF/SVG/...")

#let dd(..args) = context panic("bullseye's html.dd() must not be present when compiling a document to PDF/SVG/...")

#let del(..args) = context panic("bullseye's html.del() must not be present when compiling a document to PDF/SVG/...")

#let details(..args) = context panic("bullseye's html.details() must not be present when compiling a document to PDF/SVG/...")

#let dfn(..args) = context panic("bullseye's html.dfn() must not be present when compiling a document to PDF/SVG/...")

#let dialog(..args) = context panic("bullseye's html.dialog() must not be present when compiling a document to PDF/SVG/...")

#let div(..args) = context panic("bullseye's html.div() must not be present when compiling a document to PDF/SVG/...")

#let dl(..args) = context panic("bullseye's html.dl() must not be present when compiling a document to PDF/SVG/...")

#let dt(..args) = context panic("bullseye's html.dt() must not be present when compiling a document to PDF/SVG/...")

#let em(..args) = context panic("bullseye's html.em() must not be present when compiling a document to PDF/SVG/...")

#let embed(..args) = context panic("bullseye's html.embed() must not be present when compiling a document to PDF/SVG/...")

#let fieldset(..args) = context panic("bullseye's html.fieldset() must not be present when compiling a document to PDF/SVG/...")

#let figcaption(..args) = context panic("bullseye's html.figcaption() must not be present when compiling a document to PDF/SVG/...")

#let figure(..args) = context panic("bullseye's html.figure() must not be present when compiling a document to PDF/SVG/...")

#let footer(..args) = context panic("bullseye's html.footer() must not be present when compiling a document to PDF/SVG/...")

#let form(..args) = context panic("bullseye's html.form() must not be present when compiling a document to PDF/SVG/...")

#let h1(..args) = context panic("bullseye's html.h1() must not be present when compiling a document to PDF/SVG/...")

#let h2(..args) = context panic("bullseye's html.h2() must not be present when compiling a document to PDF/SVG/...")

#let h3(..args) = context panic("bullseye's html.h3() must not be present when compiling a document to PDF/SVG/...")

#let h4(..args) = context panic("bullseye's html.h4() must not be present when compiling a document to PDF/SVG/...")

#let h5(..args) = context panic("bullseye's html.h5() must not be present when compiling a document to PDF/SVG/...")

#let h6(..args) = context panic("bullseye's html.h6() must not be present when compiling a document to PDF/SVG/...")

#let head(..args) = context panic("bullseye's html.head() must not be present when compiling a document to PDF/SVG/...")

#let header(..args) = context panic("bullseye's html.header() must not be present when compiling a document to PDF/SVG/...")

#let hgroup(..args) = context panic("bullseye's html.hgroup() must not be present when compiling a document to PDF/SVG/...")

#let hr(..args) = context panic("bullseye's html.hr() must not be present when compiling a document to PDF/SVG/...")

#let html(..args) = context panic("bullseye's html.html() must not be present when compiling a document to PDF/SVG/...")

#let i(..args) = context panic("bullseye's html.i() must not be present when compiling a document to PDF/SVG/...")

#let iframe(..args) = context panic("bullseye's html.iframe() must not be present when compiling a document to PDF/SVG/...")

#let img(..args) = context panic("bullseye's html.img() must not be present when compiling a document to PDF/SVG/...")

#let input(..args) = context panic("bullseye's html.input() must not be present when compiling a document to PDF/SVG/...")

#let ins(..args) = context panic("bullseye's html.ins() must not be present when compiling a document to PDF/SVG/...")

#let kbd(..args) = context panic("bullseye's html.kbd() must not be present when compiling a document to PDF/SVG/...")

#let label(..args) = context panic("bullseye's html.label() must not be present when compiling a document to PDF/SVG/...")

#let legend(..args) = context panic("bullseye's html.legend() must not be present when compiling a document to PDF/SVG/...")

#let li(..args) = context panic("bullseye's html.li() must not be present when compiling a document to PDF/SVG/...")

#let link(..args) = context panic("bullseye's html.link() must not be present when compiling a document to PDF/SVG/...")

#let main(..args) = context panic("bullseye's html.main() must not be present when compiling a document to PDF/SVG/...")

#let map(..args) = context panic("bullseye's html.map() must not be present when compiling a document to PDF/SVG/...")

#let mark(..args) = context panic("bullseye's html.mark() must not be present when compiling a document to PDF/SVG/...")

#let menu(..args) = context panic("bullseye's html.menu() must not be present when compiling a document to PDF/SVG/...")

#let meta(..args) = context panic("bullseye's html.meta() must not be present when compiling a document to PDF/SVG/...")

#let meter(..args) = context panic("bullseye's html.meter() must not be present when compiling a document to PDF/SVG/...")

#let nav(..args) = context panic("bullseye's html.nav() must not be present when compiling a document to PDF/SVG/...")

#let noscript(..args) = context panic("bullseye's html.noscript() must not be present when compiling a document to PDF/SVG/...")

#let object(..args) = context panic("bullseye's html.object() must not be present when compiling a document to PDF/SVG/...")

#let ol(..args) = context panic("bullseye's html.ol() must not be present when compiling a document to PDF/SVG/...")

#let optgroup(..args) = context panic("bullseye's html.optgroup() must not be present when compiling a document to PDF/SVG/...")

#let option(..args) = context panic("bullseye's html.option() must not be present when compiling a document to PDF/SVG/...")

#let output(..args) = context panic("bullseye's html.output() must not be present when compiling a document to PDF/SVG/...")

#let p(..args) = context panic("bullseye's html.p() must not be present when compiling a document to PDF/SVG/...")

#let picture(..args) = context panic("bullseye's html.picture() must not be present when compiling a document to PDF/SVG/...")

#let pre(..args) = context panic("bullseye's html.pre() must not be present when compiling a document to PDF/SVG/...")

#let progress(..args) = context panic("bullseye's html.progress() must not be present when compiling a document to PDF/SVG/...")

#let q(..args) = context panic("bullseye's html.q() must not be present when compiling a document to PDF/SVG/...")

#let rp(..args) = context panic("bullseye's html.rp() must not be present when compiling a document to PDF/SVG/...")

#let rt(..args) = context panic("bullseye's html.rt() must not be present when compiling a document to PDF/SVG/...")

#let ruby(..args) = context panic("bullseye's html.ruby() must not be present when compiling a document to PDF/SVG/...")

#let s(..args) = context panic("bullseye's html.s() must not be present when compiling a document to PDF/SVG/...")

#let samp(..args) = context panic("bullseye's html.samp() must not be present when compiling a document to PDF/SVG/...")

#let script(..args) = context panic("bullseye's html.script() must not be present when compiling a document to PDF/SVG/...")

#let search(..args) = context panic("bullseye's html.search() must not be present when compiling a document to PDF/SVG/...")

#let section(..args) = context panic("bullseye's html.section() must not be present when compiling a document to PDF/SVG/...")

#let select(..args) = context panic("bullseye's html.select() must not be present when compiling a document to PDF/SVG/...")

#let slot(..args) = context panic("bullseye's html.slot() must not be present when compiling a document to PDF/SVG/...")

#let small(..args) = context panic("bullseye's html.small() must not be present when compiling a document to PDF/SVG/...")

#let source(..args) = context panic("bullseye's html.source() must not be present when compiling a document to PDF/SVG/...")

#let span(..args) = context panic("bullseye's html.span() must not be present when compiling a document to PDF/SVG/...")

#let strong(..args) = context panic("bullseye's html.strong() must not be present when compiling a document to PDF/SVG/...")

#let style(..args) = context panic("bullseye's html.style() must not be present when compiling a document to PDF/SVG/...")

#let sub(..args) = context panic("bullseye's html.sub() must not be present when compiling a document to PDF/SVG/...")

#let summary(..args) = context panic("bullseye's html.summary() must not be present when compiling a document to PDF/SVG/...")

#let sup(..args) = context panic("bullseye's html.sup() must not be present when compiling a document to PDF/SVG/...")

#let table(..args) = context panic("bullseye's html.table() must not be present when compiling a document to PDF/SVG/...")

#let tbody(..args) = context panic("bullseye's html.tbody() must not be present when compiling a document to PDF/SVG/...")

#let td(..args) = context panic("bullseye's html.td() must not be present when compiling a document to PDF/SVG/...")

#let template(..args) = context panic("bullseye's html.template() must not be present when compiling a document to PDF/SVG/...")

#let textarea(..args) = context panic("bullseye's html.textarea() must not be present when compiling a document to PDF/SVG/...")

#let tfoot(..args) = context panic("bullseye's html.tfoot() must not be present when compiling a document to PDF/SVG/...")

#let th(..args) = context panic("bullseye's html.th() must not be present when compiling a document to PDF/SVG/...")

#let thead(..args) = context panic("bullseye's html.thead() must not be present when compiling a document to PDF/SVG/...")

#let time(..args) = context panic("bullseye's html.time() must not be present when compiling a document to PDF/SVG/...")

#let title(..args) = context panic("bullseye's html.title() must not be present when compiling a document to PDF/SVG/...")

#let tr(..args) = context panic("bullseye's html.tr() must not be present when compiling a document to PDF/SVG/...")

#let track(..args) = context panic("bullseye's html.track() must not be present when compiling a document to PDF/SVG/...")

#let u(..args) = context panic("bullseye's html.u() must not be present when compiling a document to PDF/SVG/...")

#let ul(..args) = context panic("bullseye's html.ul() must not be present when compiling a document to PDF/SVG/...")

#let var(..args) = context panic("bullseye's html.var() must not be present when compiling a document to PDF/SVG/...")

#let video(..args) = context panic("bullseye's html.video() must not be present when compiling a document to PDF/SVG/...")

#let wbr(..args) = context panic("bullseye's html.wbr() must not be present when compiling a document to PDF/SVG/...")
